### ISSUE TITLE
Bug with compound unique index 

### ISSUE THREAD

**Issue by benjiec** [gijzelaerr/djonet#3]
I reported this bug to bugzilla, see

http://bugs.monetdb.org/show_bug.cgi?id=3091

In relation to Django, this means the ContentType models from Django won't work out of box with MonetDB. The workaround (it's a poor one, but works) is to reorder the ID field to after other field definitions. E.g.

cd python2.7/site-packages/django/contrib/contenttypes
apply the following patch

```
*** models.py.orig      Thu Jun 28 17:12:55 2012
--- models.py   Thu Jun 28 17:07:23 2012
***************
*** 121,126 ****
--- 121,127 ----
      name = models.CharField(max_length=100)
      app_label = models.CharField(max_length=100)
      model = models.CharField(_('python model class name'), max_length=100)
+     id = models.AutoField(primary_key=True)
      objects = ContentTypeManager()

      class Meta:

```

**Comment by gijzelaerr** [comment]
This is a hack of Django itself, I can't do anything about it in Djonet. 

Probably it is best to wait when this bug is solved in MonetDB.
